from pydantic import BaseModel, Field
from typing import List, Dict, Optional


class AgentState(BaseModel):
    
    patient_id: Optional[str] = Field(
        default=None,
        description="Unique identifier for the current patient"
    )
    
    user_input: str = Field(default="", description="Raw text input from the user")
    conversation_history: List[Dict[str, str]] = Field(
        default_factory=list, 
        description="History of chat messages (role and content)"
    )
    
    extracted_entities: Dict[str, str] = Field(
        default_factory=dict, 
        description="Structured data extracted from user input (e.g., age, weight, symptoms)"
    )
    
    is_emergency: bool = Field(
        default=False, 
        description="Flag indicating if the input contains emergency keywords"
    )
    
    draft_response: str = Field(
        default="", 
        description="Initial response generated by the Core Agent before validation"
    )
    
    final_response: str = Field(
        default="", 
        description="Validated and final response to be shown to the user"
    )
    supervisor_approved: bool = Field(
        default=False, 
        description="Flag indicating Supervisor has validated the draft response"
    )